---
- name: Install Apache
  apt:
   name: apache2
   state: present
   update_cache: true

- name: Deploy custom index.html
  template:
   src: index.html.j2
   dest: /var/www/html/index.html
   owner: www-data
   group: www-data
   mode: '0644'