---
- name: Install and Configure Nginx
  hosts: ubuntu
  become: true

  tasks:
   - name: Install Nginx
     ansible.builtin.apt:
      name: nginx
      state: latest
      update_cache: true

   - name: Ensure Nginx is running
     ansible.builtin.systemd_service:
      name: nginx
      state: started
      enabled: true